// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxkthdritfmvvftubfdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4a3RoZHJpdGZtdnZmdHViZmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTk1NzYsImV4cCI6MjA2MzQ5NTU3Nn0.ibJSPL2d5Q5MyvSwJ8H0VbhJhUawtNLqrMavS7R-tCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);